Swords:
 level: 100
Knives:
 level: 100
Club:
 level: 100
Polearms:
 level: 100
Spears:
 level: 100
Blocking:
 level: 100
Axes:
 level: 100
Bows:
 level: 100
Unarmed:
 level: 100
Pickaxes:
 level: 100
Woodcutting:
 level: 100
Sneak:
 level: 100
Swim:
 level: 100
Run:
 level: 100
Jump:
 level: 100
ElementalMagic:
 level: 100
BloodMagic:
 level: 100
Tenacity:
 level: 100
Vitality:
 level: 100
Packhorse:
 level: 100
Evasion:
 level: 100
Building:
 level: 100
Cooking:
 level: 100
Cartography:
 level: 100
Fitness:
 level: 100
Athletics:
 level: 100
Gathering:
 level: 100
Sailing:
 level: 100
Discipline:
 level: 100
Abjuration:
 level: 100
Alteration:
 level: 100
Conjuration:
 level: 100
Evocation:
 level: 100
Illusion:
 level: 100
Crossbows:
 level: 100
Jewelcrafting:
 level: 100
